[tools]
rust = "stable"
node = "22"
pnpm = "latest"
just = "latest"
"cargo:wasm-pack" = "latest"
"cargo:typos-cli" = "latest"
"cargo:committed" = "latest"
"cargo:watchexec-cli" = "latest"
"ubi:DarthSim/hivemind" = "latest"
