packages:
  - apps/*
  - packages/*

catalog:
  '@tanstack/react-hotkeys': ^0.3.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~5.9.3
  vite: ^7.3.1
