packages:
  - apps/*
  - packages/*
  - vendor/design/packages/*

allowBuilds:
  "@swc/core": true
  esbuild: true
  lefthook: true

catalog:
  "@floating-ui/react": ^0.27.19
  "@tanstack/react-hotkeys": ^0.8.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  lucide-react: ^1.7.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ~6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.24
  vite-plus: ^0.2.2
overrides:
  "@tanstack/virtual-core": "3.17.3"
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
