// AUTO-GENERATED by harmony codegen. Do not edit.
// Regenerate: harmony codegen
/* eslint-disable */

import * as wasm from "@harmony/wasm";
import type {
  CreateRoomInput,
  CreateSpaceInput,
  EditMessageInput,
  FocusOnEventInput,
  ListDiff,
  LoginRequest,
  MediaUploadInput,
  MediaUploaded,
  MemberData,
  ModeSwapResult,
  PaginateInput,
  PaginateResult,
  RedactMessageInput,
  RestoreRequest,
  RoomData,
  RoomDataWithSpace,
  RoomStateSnapshot,
  SendMessageInput,
  SessionData,
  SpaceData,
  SyncStatus,
  TimelineStreamMessage,
  ToggleReactionInput,
} from "@harmony/wasm";
import type { RpcResult } from "../transport";

export type RpcFn<I, O> = (input: I) => Promise<RpcResult<O>>;
export type CommandFn<I> = (input: I) => Promise<RpcResult<void>>;
export type SubscriptionFn<I, Init, Chunk> = (input: I) => Promise<{ ok: true; initial: Init; stream: ReadableStream<Chunk> } | { ok: false; error: import("../transport").HarmonyError }>;

export const rpc = {
  "auth.login": wasm.authLogin as RpcFn<LoginRequest, SessionData>,
  "auth.restore": wasm.authRestoreSession as RpcFn<RestoreRequest, SessionData>,
  "diagnostics.ping": wasm.diagnosticsPing as RpcFn<void, string>,
  "lifecycle.warm": wasm.lifecycleWarm as RpcFn<void, void>,
  "media.upload": wasm.mediaUpload as RpcFn<MediaUploadInput, MediaUploaded>,
  "members.get": wasm.membersGetMembers as RpcFn<string, MemberData[]>,
  "rooms.get_all": wasm.roomsGetAll as RpcFn<void, RoomDataWithSpace[]>,
  "spaces.create": wasm.spacesCreateSpace as RpcFn<CreateSpaceInput, SpaceData>,
  "spaces.create_room": wasm.spacesCreateRoom as RpcFn<CreateRoomInput, RoomData>,
  "spaces.descendants": wasm.spacesGetDescendants as RpcFn<string, string[]>,
  "spaces.get": wasm.spacesGet as RpcFn<void, SpaceData[]>,
  "timeline.edit": wasm.timelineEditMessage as RpcFn<EditMessageInput, void>,
  "timeline.focus_on_event": wasm.timelineFocusOnEvent as RpcFn<FocusOnEventInput, ModeSwapResult>,
  "timeline.get_room_state": wasm.timelineGetRoomState as RpcFn<string, RoomStateSnapshot>,
  "timeline.paginate": wasm.timelinePaginateRoom as RpcFn<PaginateInput, PaginateResult>,
  "timeline.redact": wasm.timelineRedactMessage as RpcFn<RedactMessageInput, void>,
  "timeline.return_to_live": wasm.timelineReturnToLive as RpcFn<string, ModeSwapResult>,
  "timeline.send": wasm.timelineSendMessage as RpcFn<SendMessageInput, void>,
  "timeline.toggle_reaction": wasm.timelineToggleReaction as RpcFn<ToggleReactionInput, boolean>,
} as const;

export const commands = {
  "auth.logout": wasm.authLogout as CommandFn<void>,
  "sync.stop": wasm.syncStopSync as CommandFn<void>,
  "timeline.mark_as_read": wasm.timelineMarkAsRead as CommandFn<string>,
} as const;

export const subscriptions = {
  "members.subscribe": { fn: wasm.membersSubscribeMembers as SubscriptionFn<string, MemberData[], ListDiff<MemberData>> },
  "rooms.subscribe_in_space": { fn: wasm.roomsSubscribeInSpace as SubscriptionFn<string, RoomData[], ListDiff<RoomData>> },
  "spaces.subscribe": { fn: wasm.spacesSubscribe as SubscriptionFn<void, SpaceData[], ListDiff<SpaceData>> },
  "sync.start": { fn: wasm.syncStartSync as SubscriptionFn<void, void, SyncStatus> },
  "timeline.subscribe": { fn: wasm.timelineSubscribeRoom as SubscriptionFn<string, RoomStateSnapshot, TimelineStreamMessage> },
} as const;
