// This file has been generated by Specta. Do not edit this file manually.
export type Attachment = {
	body: string,
	msgtype: string,
	filename: string | null,
	url: string | null,
	file: unknown | null,
	format: string | null,
	formattedBody: string | null,
	info: AttachmentInfo | null,
};

/**
 *  Flattened media metadata. Mirrors the fields the client reads across every
 *  `m.*` attachment kind; ruma's per-type info structs aren't carried on the
 *  wire (they don't implement `specta::Type`).
 */
export type AttachmentInfo = {
	width: number | null,
	height: number | null,
	durationMs: number | null,
	size: number | null,
	mimetype: string | null,
};

export type ChannelVisibility = "public" | "private";

export type CreateRoomInput = {
	spaceId: string,
	name: string,
	visibility: ChannelVisibility,
};

export type CreateSpaceInput = {
	name: string,
	avatarBytes: number[] | null,
	avatarContentType: string | null,
};

export type EditMessageInput = {
	roomId: string,
	eventId: string | null,
	transactionId: string | null,
	body: string,
	formattedBody: string | null,
};

export type FocusOnEventInput = {
	roomId: string,
	targetEventId: string,
	numContextEvents: number | null,
};

/**
 *  Universal error type carried by `Rpc<T>` and `Command` across the
 *  Harmony bridge. Serialized as a `{ code, ... }` discriminated union.
 */
export type HarmonyError = { code: "invalidCredentials" } | { code: "serverNotFound" } | { code: "networkError"; message: string } | { code: "rateLimited" } | { code: "authFailed" } | { code: "roomNotFound" } | { code: "invalidUserId" } | { code: "invalidRoomId" } | { code: "invalidEventId" } | { code: "invalidContentType" } | { code: "clientNotReady" } | { code: "clientAlreadyInitialized" } | { code: "serializationFailed"; message: string } | { code: "unknown"; message: string };

/**
 *  Wire-shape diff for `Vec<T>`-style subscriptions. Mirrors the variants
 *  of `matrix_sdk_ui::eyeball_im::VectorDiff` so the worker can forward
 *  shape-by-shape without re-encoding.
 * 
 *  Carries `#[derive]`s manually rather than going through `#[harmony]`
 *  because `ListDiff<T>` is generic; the wasm-bindgen ABI is realised by
 *  each concrete chunk type at the `Subscription<I, ListDiff<T>>` boundary,
 *  not by `ListDiff` itself.
 */
export type ListDiff<T> = { op: "append"; values: T[] } | { op: "clear" } | { op: "push_front"; value: T } | { op: "push_back"; value: T } | { op: "pop_front" } | { op: "pop_back" } | { op: "insert"; index: number; value: T } | { op: "set"; index: number; value: T } | { op: "remove"; index: number } | { op: "truncate"; length: number } | { op: "reset"; values: T[] };

export type LoginRequest = {
	homeserver: string,
	username: string,
	password: string,
};

export type MediaContent = {
	bytes: Uint8Array<ArrayBuffer>,
	contentType: string,
};

export type MediaFetchInput = {
	file: unknown,
	contentType: string | null,
};

export type MediaUploadInput = {
	data: Uint8Array<ArrayBuffer>,
	contentType: string | null,
};

export type MediaUploaded = {
	mxUrl: string,
};

export type MemberData = {
	userId: string,
	displayName: string | null,
	avatarUrl: string | null,
};

export type Mentions = {
	everyone: boolean,
	userIds: string[],
};

export type ModeSwapResult = {
	events: TimelineEventData[],
	mode: TimelineMode,
	generation: number,
};

export type PaginateInput = {
	roomId: string,
	direction: PaginationDirection,
	count: number,
};

export type PaginateResult = {
	exhausted: boolean,
	mode: TimelineMode,
	events: TimelineEventData[] | null,
	generation: number | null,
};

export type PaginationDirection = "forward" | "backward";

export type ReactionGroup = {
	key: string,
	count: number,
	senders: string[],
	pending: boolean,
};

export type RedactMessageInput = {
	room: string,
	event: string | null,
	transaction: string | null,
};

export type ReplyTarget = {
	eventId: string,
	sender: string | null,
	senderName: string | null,
	body: string | null,
	redacted: boolean,
};

export type RestoreRequest = {
	homeserver: string,
	userId: string,
	deviceId: string,
	accessToken: string,
	refreshToken: string | null,
};

export type RoomData = {
	roomId: string,
	displayName: string,
	roomType: string | null,
	unreadCount: number,
	mentionCount: number,
};

export type RoomDataWithSpace = {
	roomId: string,
	displayName: string,
	unreadCount: number,
	mentionCount: number,
	parentSpace: SpaceData | null,
};

export type RoomStateSnapshot = {
	events: TimelineEventData[],
	mode: TimelineMode,
	generation: number,
};

export type SendMessageInput = {
	roomId: string,
	body: string,
	formattedBody: string | null,
	replyToEventId: string | null,
	attachments: Attachment[] | null,
};

export type SendState = { state: "notSentYet" } | { state: "sent" } | { state: "sendingFailed"; error: string; isRecoverable: boolean };

export type SessionData = {
	homeserver: string,
	userId: string,
	deviceId: string,
	accessToken: string,
	refreshToken: string | null,
};

export type SpaceData = {
	roomId: string,
	displayName: string,
	avatarUrl: string | null,
};

export type SyncStatus = "syncing" | "stopped" | "reconnecting" | "error";

export type TimelineContent = { type: "message"; body: string; formattedBody: string | null; msgtype: string; mentions: Mentions | null; edited: boolean; attachments: Attachment[] | null } | { type: "membershipChange"; userId: string; change: string } | { type: "profileChange"; displayNameChange: string | null; avatarUrlChange: string | null } | { type: "state"; eventType: string } | { type: "virtual"; kind: string } | { type: "unknown" };

export type TimelineEventData = {
	id: string | null,
	transactionId: string | null,
	sender: string | null,
	senderName: string | null,
	senderAvatar: string | null,
	timestamp: number,
	content: TimelineContent,
	sendState: SendState | null,
	reactions: ReactionGroup[] | null,
	replyTo: ReplyTarget | null,
};

export type TimelineMode = "live" | "detached";

export type TimelineStreamMessage = { kind: "diffs"; generation: number; diffs: ListDiff<TimelineEventData>[] } | { kind: "error"; message: string };

export type ToggleReactionInput = {
	roomId: string,
	eventId: string | null,
	transactionId: string | null,
	key: string,
};
