// AUTO-GENERATED by harmony codegen. Do not edit.
// Stub: native transport not yet wired. Populate when the binding lands.
/* eslint-disable */

import type { RpcMap, CommandMap, SubscriptionMap } from "@harmony/core/protocol/maps.generated";

export const nativeRpc: Partial<RpcMap> = {};

export const nativeCommands: Partial<CommandMap> = {};

export const nativeSubscriptions: Partial<SubscriptionMap> = {};
