/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as InviteCodeRouteImport } from "./routes/invite/$code";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedChatRouteImport } from "./routes/_authenticated/_chat";
import { Route as AuthenticatedChatIndexRouteImport } from "./routes/_authenticated/_chat/index";
import { Route as AuthenticatedChatSpaceIdRouteRouteImport } from "./routes/_authenticated/_chat/$spaceId/route";
import { Route as AuthenticatedChatSpaceIdRoomIdRouteImport } from "./routes/_authenticated/_chat/$spaceId/$roomId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: "/_chat",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedChatRoute,
} as any);
const AuthenticatedChatSpaceIdRouteRoute =
  AuthenticatedChatSpaceIdRouteRouteImport.update({
    id: "/$spaceId",
    path: "/$spaceId",
    getParentRoute: () => AuthenticatedChatRoute,
  } as any);
const AuthenticatedChatSpaceIdRoomIdRoute =
  AuthenticatedChatSpaceIdRoomIdRouteImport.update({
    id: "/$roomId",
    path: "/$roomId",
    getParentRoute: () => AuthenticatedChatSpaceIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedChatIndexRoute;
  "/login": typeof LoginRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/invite/$code": typeof InviteCodeRoute;
  "/$spaceId": typeof AuthenticatedChatSpaceIdRouteRouteWithChildren;
  "/$spaceId/$roomId": typeof AuthenticatedChatSpaceIdRoomIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedChatIndexRoute;
  "/login": typeof LoginRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/invite/$code": typeof InviteCodeRoute;
  "/$spaceId": typeof AuthenticatedChatSpaceIdRouteRouteWithChildren;
  "/$spaceId/$roomId": typeof AuthenticatedChatSpaceIdRoomIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/_chat": typeof AuthenticatedChatRouteWithChildren;
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute;
  "/invite/$code": typeof InviteCodeRoute;
  "/_authenticated/_chat/$spaceId": typeof AuthenticatedChatSpaceIdRouteRouteWithChildren;
  "/_authenticated/_chat/": typeof AuthenticatedChatIndexRoute;
  "/_authenticated/_chat/$spaceId/$roomId": typeof AuthenticatedChatSpaceIdRoomIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/settings"
    | "/invite/$code"
    | "/$spaceId"
    | "/$spaceId/$roomId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/settings"
    | "/invite/$code"
    | "/$spaceId"
    | "/$spaceId/$roomId";
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/_chat"
    | "/_authenticated/settings"
    | "/invite/$code"
    | "/_authenticated/_chat/$spaceId"
    | "/_authenticated/_chat/"
    | "/_authenticated/_chat/$spaceId/$roomId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  InviteCodeRoute: typeof InviteCodeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof InviteCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_chat": {
      id: "/_authenticated/_chat";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_chat/": {
      id: "/_authenticated/_chat/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport;
      parentRoute: typeof AuthenticatedChatRoute;
    };
    "/_authenticated/_chat/$spaceId": {
      id: "/_authenticated/_chat/$spaceId";
      path: "/$spaceId";
      fullPath: "/$spaceId";
      preLoaderRoute: typeof AuthenticatedChatSpaceIdRouteRouteImport;
      parentRoute: typeof AuthenticatedChatRoute;
    };
    "/_authenticated/_chat/$spaceId/$roomId": {
      id: "/_authenticated/_chat/$spaceId/$roomId";
      path: "/$roomId";
      fullPath: "/$spaceId/$roomId";
      preLoaderRoute: typeof AuthenticatedChatSpaceIdRoomIdRouteImport;
      parentRoute: typeof AuthenticatedChatSpaceIdRouteRoute;
    };
  }
}

interface AuthenticatedChatSpaceIdRouteRouteChildren {
  AuthenticatedChatSpaceIdRoomIdRoute: typeof AuthenticatedChatSpaceIdRoomIdRoute;
}

const AuthenticatedChatSpaceIdRouteRouteChildren: AuthenticatedChatSpaceIdRouteRouteChildren =
  {
    AuthenticatedChatSpaceIdRoomIdRoute: AuthenticatedChatSpaceIdRoomIdRoute,
  };

const AuthenticatedChatSpaceIdRouteRouteWithChildren =
  AuthenticatedChatSpaceIdRouteRoute._addFileChildren(
    AuthenticatedChatSpaceIdRouteRouteChildren,
  );

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatSpaceIdRouteRoute: typeof AuthenticatedChatSpaceIdRouteRouteWithChildren;
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute;
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatSpaceIdRouteRoute:
    AuthenticatedChatSpaceIdRouteRouteWithChildren,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
};

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteCodeRoute: InviteCodeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
