/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedChatRouteImport } from "./routes/_authenticated/_chat";
import { Route as AuthenticatedChatIndexRouteImport } from "./routes/_authenticated/_chat/index";
import { Route as AuthenticatedChatChannelsChannelIdRouteImport } from "./routes/_authenticated/_chat/channels/$channelId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: "/_chat",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedChatRoute,
} as any);
const AuthenticatedChatChannelsChannelIdRoute =
  AuthenticatedChatChannelsChannelIdRouteImport.update({
    id: "/channels/$channelId",
    path: "/channels/$channelId",
    getParentRoute: () => AuthenticatedChatRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedChatIndexRoute;
  "/login": typeof LoginRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/channels/$channelId": typeof AuthenticatedChatChannelsChannelIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedChatIndexRoute;
  "/login": typeof LoginRoute;
  "/settings": typeof AuthenticatedSettingsRoute;
  "/channels/$channelId": typeof AuthenticatedChatChannelsChannelIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/_chat": typeof AuthenticatedChatRouteWithChildren;
  "/_authenticated/settings": typeof AuthenticatedSettingsRoute;
  "/_authenticated/_chat/": typeof AuthenticatedChatIndexRoute;
  "/_authenticated/_chat/channels/$channelId": typeof AuthenticatedChatChannelsChannelIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/settings" | "/channels/$channelId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/settings" | "/channels/$channelId";
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/_chat"
    | "/_authenticated/settings"
    | "/_authenticated/_chat/"
    | "/_authenticated/_chat/channels/$channelId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_chat": {
      id: "/_authenticated/_chat";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_chat/": {
      id: "/_authenticated/_chat/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport;
      parentRoute: typeof AuthenticatedChatRoute;
    };
    "/_authenticated/_chat/channels/$channelId": {
      id: "/_authenticated/_chat/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof AuthenticatedChatChannelsChannelIdRouteImport;
      parentRoute: typeof AuthenticatedChatRoute;
    };
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute;
  AuthenticatedChatChannelsChannelIdRoute: typeof AuthenticatedChatChannelsChannelIdRoute;
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedChatChannelsChannelIdRoute:
    AuthenticatedChatChannelsChannelIdRoute,
};

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
