CREATE TABLE "custom_statuses" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mxid" TEXT NOT NULL,
    "emoji_name" TEXT,
    "emoji_id" TEXT,
    "emoji_animated" BOOLEAN NOT NULL,
    "text" TEXT,
    "expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_custom_statuses_by_mxid" ON "custom_statuses" ("mxid");
CREATE TABLE "invite_links" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" TEXT NOT NULL,
    "space_mxid" TEXT NOT NULL,
    "creator_mxid" TEXT NOT NULL,
    "max_uses" BIGINT,
    "use_count" BIGINT NOT NULL,
    "expires_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_invite_links_by_code" ON "invite_links" ("code");
