// AUTO-GENERATED by harmony codegen. Do not edit.
// Regenerate: harmony codegen
/* eslint-disable */

import { invokeCommand, invokeRpc, invokeRpcBytesIn, invokeRpcBytesOut } from "./invoke";
import { subscribeViaTauri } from "./subscribe";
import type { CommandMap, RpcMap, SubscriptionMap } from "@harmony/core/protocol/maps.generated";

export const tauriRpc: { [K in keyof RpcMap]: RpcMap[K] } = {
  "auth.login": ((input) => invokeRpc("auth_login", input)) as RpcMap["auth.login"],
  "auth.restore": ((input) => invokeRpc("auth_restore", input)) as RpcMap["auth.restore"],
  "diagnostics.ping": ((input) => invokeRpc("diagnostics_ping", input)) as RpcMap["diagnostics.ping"],
  "lifecycle.warm": ((input) => invokeRpc("lifecycle_warm", input)) as RpcMap["lifecycle.warm"],
  "media.fetch": ((input) => invokeRpcBytesOut("media_fetch", input, "bytes")) as RpcMap["media.fetch"],
  "media.upload": ((input) => invokeRpcBytesIn("media_upload", input, "data")) as RpcMap["media.upload"],
  "members.get": ((input) => invokeRpc("members_get", input)) as RpcMap["members.get"],
  "rooms.get_all": ((input) => invokeRpc("rooms_get_all", input)) as RpcMap["rooms.get_all"],
  "spaces.create": ((input) => invokeRpc("spaces_create", input)) as RpcMap["spaces.create"],
  "spaces.create_room": ((input) => invokeRpc("spaces_create_room", input)) as RpcMap["spaces.create_room"],
  "spaces.descendants": ((input) => invokeRpc("spaces_descendants", input)) as RpcMap["spaces.descendants"],
  "spaces.get": ((input) => invokeRpc("spaces_get", input)) as RpcMap["spaces.get"],
  "timeline.edit": ((input) => invokeRpc("timeline_edit", input)) as RpcMap["timeline.edit"],
  "timeline.focus_on_event": ((input) => invokeRpc("timeline_focus_on_event", input)) as RpcMap["timeline.focus_on_event"],
  "timeline.get_room_state": ((input) => invokeRpc("timeline_get_room_state", input)) as RpcMap["timeline.get_room_state"],
  "timeline.paginate": ((input) => invokeRpc("timeline_paginate", input)) as RpcMap["timeline.paginate"],
  "timeline.redact": ((input) => invokeRpc("timeline_redact", input)) as RpcMap["timeline.redact"],
  "timeline.return_to_live": ((input) => invokeRpc("timeline_return_to_live", input)) as RpcMap["timeline.return_to_live"],
  "timeline.send": ((input) => invokeRpc("timeline_send", input)) as RpcMap["timeline.send"],
  "timeline.toggle_reaction": ((input) => invokeRpc("timeline_toggle_reaction", input)) as RpcMap["timeline.toggle_reaction"],
};

export const tauriCommands: { [K in keyof CommandMap]: CommandMap[K] } = {
  "auth.logout": ((input) => invokeCommand("auth_logout", input)) as CommandMap["auth.logout"],
  "sync.stop": ((input) => invokeCommand("sync_stop", input)) as CommandMap["sync.stop"],
  "timeline.mark_as_read": ((input) => invokeCommand("timeline_mark_as_read", input)) as CommandMap["timeline.mark_as_read"],
};

export const tauriSubscriptions: { [K in keyof SubscriptionMap]: SubscriptionMap[K] } = {
  "members.subscribe": { fn: ((input) => subscribeViaTauri("members_subscribe", input)) as SubscriptionMap["members.subscribe"]["fn"], snapshot: "members.get" },
  "rooms.subscribe_in_space": { fn: ((input) => subscribeViaTauri("rooms_subscribe_in_space", input)) as SubscriptionMap["rooms.subscribe_in_space"]["fn"] },
  "spaces.subscribe": { fn: ((input) => subscribeViaTauri("spaces_subscribe", input)) as SubscriptionMap["spaces.subscribe"]["fn"], snapshot: "spaces.get" },
  "sync.start": { fn: ((input) => subscribeViaTauri("sync_start", input)) as SubscriptionMap["sync.start"]["fn"] },
  "timeline.subscribe": { fn: ((input) => subscribeViaTauri("timeline_subscribe", input)) as SubscriptionMap["timeline.subscribe"]["fn"], snapshot: "timeline.get_room_state" },
};
