use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};
use serde::{Deserialize, Serialize};
use walrus::IdsToIndices;

use crate::util::repo::workspace_root;

const SECTION: &str = "__harmony_protocol";
const WASM_CRATE: &str = "crates/wasm";
const WASM_OUT_DIR: &str = "packages/wasm";
const WASM_BG_PATH: &str = "packages/wasm/wasm_bg.wasm";
const OUTPUT_PATH: &str = "packages/core/lib/protocol/maps.generated.ts";

#[derive(Debug, Deserialize, Serialize)]
struct Entry {
    wire: String,
    js: String,
    kind: Kind,
    #[serde(default = "void_ts")]
    input_ts: String,
    #[serde(default)]
    output_ts: Option<String>,
    #[serde(default)]
    initial_ts: Option<String>,
    #[serde(default)]
    chunk_ts: Option<String>,
    #[serde(default)]
    snapshot_for: Option<String>,
    #[serde(default)]
    wasm_types: Vec<String>,
}

fn void_ts() -> String {
    "void".into()
}

#[derive(Debug, Deserialize, Serialize, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum Kind {
    Rpc,
    Command,
    Subscription,
}

pub fn run(release: bool) -> Result<()> {
    let root = workspace_root()?;
    let wasm_path = root.join(WASM_BG_PATH);
    let output_path = root.join(OUTPUT_PATH);

    build_wasm(&root, release)?;

    let entries = read_section(&wasm_path)?;
    let generated = render(&entries);

    std::fs::create_dir_all(
        output_path
            .parent()
            .ok_or_else(|| anyhow!("output path has no parent"))?,
    )?;
    std::fs::write(&output_path, generated)
        .with_context(|| format!("writing {}", output_path.display()))?;

    eprintln!(
        "harmony codegen: wrote {} entries to {}",
        entries.len(),
        output_path.display()
    );
    Ok(())
}

fn build_wasm(root: &Path, release: bool) -> Result<()> {
    let crate_path = root.join(WASM_CRATE);
    let out_dir = root.join(WASM_OUT_DIR);

    let mut cmd = Command::new("wasm-pack");
    cmd.arg("build")
        .arg(&crate_path)
        .arg("--target")
        .arg("web")
        .arg("--scope")
        .arg("harmony")
        .arg("--out-dir")
        .arg(&out_dir);
    if !release {
        cmd.arg("--dev");
    }

    let status = cmd
        .status()
        .context("failed to spawn `wasm-pack` — is it installed and on PATH?")?;
    if !status.success() {
        bail!("wasm-pack exited with status {status}");
    }
    Ok(())
}

fn read_section(wasm_path: &Path) -> Result<Vec<Entry>> {
    let module = walrus::Module::from_file(wasm_path)
        .with_context(|| format!("parsing {}", wasm_path.display()))?;
    let Some(section) = module
        .customs
        .iter()
        .find(|(_, c)| c.name() == SECTION)
        .map(|(_, c)| c)
    else {
        return Ok(Vec::new());
    };
    let raw = section.data(&IdsToIndices::default()).into_owned();
    parse_ndjson(&raw)
}

fn parse_ndjson(bytes: &[u8]) -> Result<Vec<Entry>> {
    let text = std::str::from_utf8(bytes).context("custom section is not valid UTF-8")?;
    let mut entries = Vec::new();
    for (idx, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let entry: Entry =
            serde_json::from_str(line).with_context(|| format!("parsing entry {idx}: {line}"))?;
        entries.push(entry);
    }
    Ok(entries)
}

fn render(entries: &[Entry]) -> String {
    let mut by_kind: BTreeMap<&'static str, Vec<&Entry>> = BTreeMap::new();
    by_kind.insert("rpc", Vec::new());
    by_kind.insert("commands", Vec::new());
    by_kind.insert("subscriptions", Vec::new());
    let mut referenced: BTreeSet<&str> = BTreeSet::new();

    for entry in entries {
        let key = match entry.kind {
            Kind::Rpc => "rpc",
            Kind::Command => "commands",
            Kind::Subscription => "subscriptions",
        };
        by_kind.get_mut(key).expect("preinserted").push(entry);
        for name in &entry.wasm_types {
            referenced.insert(name.as_str());
        }
    }
    for list in by_kind.values_mut() {
        list.sort_by(|a, b| a.wire.cmp(&b.wire));
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by harmony codegen. Do not edit.\n");
    out.push_str("// Regenerate: harmony codegen\n");
    out.push_str("/* eslint-disable */\n\n");
    out.push_str("import * as wasm from \"@harmony/wasm\";\n");
    if !referenced.is_empty() {
        out.push_str("import type {\n");
        for name in &referenced {
            writeln!(out, "  {name},").expect("string write");
        }
        out.push_str("} from \"@harmony/wasm\";\n");
    }
    out.push_str("import type { RpcResult } from \"../transport\";\n\n");

    out.push_str("export type RpcFn<I, O> = (input: I) => Promise<RpcResult<O>>;\n");
    out.push_str("export type CommandFn<I> = (input: I) => Promise<RpcResult<void>>;\n");
    out.push_str("export type SubscriptionFn<I, Init, Chunk> = (input: I) => Promise<{ ok: true; initial: Init; stream: ReadableStream<Chunk> } | { ok: false; error: import(\"../transport\").HarmonyError }>;\n\n");

    out.push_str("export const rpc = {\n");
    for entry in by_kind.get("rpc").expect("preinserted") {
        let output = entry.output_ts.as_deref().unwrap_or("void");
        writeln!(
            out,
            "  {wire:?}: wasm.{js} as RpcFn<{input}, {output}>,",
            wire = entry.wire,
            js = entry.js,
            input = entry.input_ts,
        )
        .expect("string write");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const commands = {\n");
    for entry in by_kind.get("commands").expect("preinserted") {
        writeln!(
            out,
            "  {wire:?}: wasm.{js} as CommandFn<{input}>,",
            wire = entry.wire,
            js = entry.js,
            input = entry.input_ts,
        )
        .expect("string write");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const subscriptions = {\n");
    for entry in by_kind.get("subscriptions").expect("preinserted") {
        let initial = entry.initial_ts.as_deref().unwrap_or("unknown");
        let chunk = entry.chunk_ts.as_deref().unwrap_or("unknown");
        let snapshot = entry
            .snapshot_for
            .as_deref()
            .map(|s| format!(", snapshot: {s:?}"))
            .unwrap_or_default();
        writeln!(
            out,
            "  {wire:?}: {{ fn: wasm.{js} as SubscriptionFn<{input}, {initial}, {chunk}>{snapshot} }},",
            wire = entry.wire,
            js = entry.js,
            input = entry.input_ts,
        )
        .expect("string write");
    }
    out.push_str("} as const;\n");

    out
}
