use std::path::Path;

use anyhow::{Context, Result, anyhow};
use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use std::collections::BTreeMap;

use super::entries::{EntryRow, group_by_kind, snapshot_map};

const TAURI_DISPATCH_OUTPUT_PATH: &str = "packages/core/lib/transport/tauri/dispatch.generated.ts";
const HANDLERS_OUTPUT_PATH: &str = "crates/harmony-bindings-desktop/src/handlers.generated.rs";

/// Run the desktop target: write the populated Tauri dispatch table
/// (frontend invoke glue) and the Rust handler-list macro consumed by
/// the binding crate.
pub(super) fn run(root: &Path, entries: &[EntryRow]) -> Result<()> {
    write_with_dirs(
        &root.join(TAURI_DISPATCH_OUTPUT_PATH),
        render_tauri_dispatch(entries),
    )?;
    write_with_dirs(&root.join(HANDLERS_OUTPUT_PATH), render_handlers(entries))?;
    Ok(())
}

fn write_with_dirs(path: &Path, contents: String) -> Result<()> {
    std::fs::create_dir_all(
        path.parent()
            .ok_or_else(|| anyhow!("desktop output path has no parent"))?,
    )?;
    std::fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

/// Tauri dispatch table. Each wire entry routes to its
/// `wire.replace('.', '_')` Tauri command through the hand-written
/// `invokeRpc` / `invokeCommand` / `subscribeViaTauri` helpers.
fn render_tauri_dispatch(entries: &[EntryRow]) -> String {
    let by_kind = group_by_kind(entries);
    let rpc_dispatch = rpc_body(&by_kind[&EntryKind::Rpc]);
    let command_dispatch = command_body(&by_kind[&EntryKind::Command]);
    let subscription_dispatch =
        subscription_body(&by_kind[&EntryKind::Subscription], &snapshot_map(entries));

    formatdoc! {r#"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen
        /* eslint-disable */

        import {{ invokeCommand, invokeRpc }} from "./invoke";
        import {{ subscribeViaTauri }} from "./subscribe";
        import type {{ CommandMap, RpcMap, SubscriptionMap }} from "../../protocol/maps.generated";

        export const tauriRpc: {{ [K in keyof RpcMap]: RpcMap[K] }} = {{
        {rpc_dispatch}
        }};

        export const tauriCommands: {{ [K in keyof CommandMap]: CommandMap[K] }} = {{
        {command_dispatch}
        }};

        export const tauriSubscriptions: {{ [K in keyof SubscriptionMap]: SubscriptionMap[K] }} = {{
        {subscription_dispatch}
        }};
    "#}
}

/// Desktop handler list. Each `#[harmony_export]` gets a
/// `#[tauri::command]` wrapper fn in its source module (see
/// `harmony-protocol-macros::export::build_desktop_wrapper`).
/// Subscriptions additionally take `subscription_id` +
/// `Channel<StreamEvent<C>>`. The builtin `harmony_unsubscribe` cancels
/// a subscription pump by id.
///
/// The generated macro expands to `::tauri::generate_handler![...]` over
/// every wrapper plus the builtin, so the consuming Tauri app calls
/// `harmony_handlers!()` once.
fn render_handlers(entries: &[EntryRow]) -> String {
    // Paths are `$crate`-relative so the only crate a Tauri shell needs to
    // depend on is the binding crate (which `pub use`s harmony-protocol).
    let mut lines: Vec<String> = vec!["        $crate::desktop::harmony_unsubscribe,".into()];
    lines.extend(
        entries
            .iter()
            .sorted_by(|a, b| a.wire.cmp(b.wire))
            .map(|e| {
                let module = e.module.replace("harmony_protocol", "$crate");
                format!("        {}::{},", module, e.wire.replace('.', "_"))
            }),
    );
    let body = lines.join("\n");

    formatdoc! {"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen

        #[macro_export]
        macro_rules! harmony_handlers {{
            () => {{
                ::tauri::generate_handler![
        {body}
                ]
            }};
        }}
    "}
}

fn rpc_body(rpc: &[&EntryRow]) -> String {
    rpc.iter()
        .map(|e| {
            let cmd = e.wire.replace('.', "_");
            format!(
                r#"  "{wire}": ((input) => invokeRpc("{cmd}", input)) as RpcMap["{wire}"],"#,
                wire = e.wire,
            )
        })
        .join("\n")
}

fn command_body(cmd: &[&EntryRow]) -> String {
    cmd.iter()
        .map(|e| {
            let tauri_cmd = e.wire.replace('.', "_");
            format!(
                r#"  "{wire}": ((input) => invokeCommand("{tauri_cmd}", input)) as CommandMap["{wire}"],"#,
                wire = e.wire,
            )
        })
        .join("\n")
}

fn subscription_body(sub: &[&EntryRow], snapshots: &BTreeMap<&str, &str>) -> String {
    sub.iter()
        .map(|e| {
            let cmd = e.wire.replace('.', "_");
            let snapshot = snapshots
                .get(e.wire)
                .map(|s| format!(r#", snapshot: "{s}""#))
                .unwrap_or_default();
            format!(
                r#"  "{wire}": {{ fn: ((input) => subscribeViaTauri("{cmd}", input)) as SubscriptionMap["{wire}"]["fn"]{snapshot} }},"#,
                wire = e.wire,
            )
        })
        .join("\n")
}
