use std::path::Path;

use anyhow::{Context, Result, anyhow};
use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use super::dispatch::{self, DispatchTable};
use super::entries::EntryRow;

const TAURI_DISPATCH_OUTPUT_PATH: &str = "apps/web/src/transport/tauri/dispatch.generated.ts";
const HANDLERS_OUTPUT_PATH: &str = "apps/desktop/src/handlers.generated.rs";

/// Run the desktop target: write the populated Tauri dispatch table
/// (frontend invoke glue) and the Rust handler-list macro included by
/// the Tauri shell.
pub(super) fn run(root: &Path, entries: &[EntryRow]) -> Result<()> {
    write_with_dirs(
        &root.join(TAURI_DISPATCH_OUTPUT_PATH),
        dispatch::render(&TAURI_TABLE, entries),
    )?;
    write_with_dirs(&root.join(HANDLERS_OUTPUT_PATH), render_handlers(entries))?;
    Ok(())
}

fn write_with_dirs(path: &Path, contents: String) -> Result<()> {
    std::fs::create_dir_all(
        path.parent()
            .ok_or_else(|| anyhow!("desktop output path has no parent"))?,
    )?;
    std::fs::write(path, contents).with_context(|| format!("writing {}", path.display()))
}

/// Tauri dispatch table. Each wire entry routes to its
/// `wire.replace('.', '_')` Tauri command through the hand-written
/// `invokeRpc` / `invokeCommand` / `subscribeViaTauri` helpers.
const TAURI_IMPORTS: &str = r#"import { invokeCommand, invokeRpc, invokeRpcBytesIn, invokeRpcBytesOut } from "./invoke";
import { subscribeViaTauri } from "./subscribe";
import type { CommandMap, RpcMap, SubscriptionMap } from "@harmony/core/protocol/maps.generated";"#;

const TAURI_TABLE: DispatchTable = DispatchTable {
    prefix: "tauri",
    imports: TAURI_IMPORTS,
    call: Some(tauri_call),
};

/// Every wire entry routes through a hand-written invoke helper, keyed by
/// the `wire.replace('.', '_')` Tauri command id.
fn tauri_call(entry: &EntryRow, kind: EntryKind) -> String {
    let cmd = entry.wire.replace('.', "_");
    match kind {
        EntryKind::Rpc => match (entry.bytes_in, entry.bytes_out) {
            (Some(field), _) => {
                format!(r#"((input) => invokeRpcBytesIn("{cmd}", input, "{field}"))"#)
            }
            (_, Some(field)) => {
                format!(r#"((input) => invokeRpcBytesOut("{cmd}", input, "{field}"))"#)
            }
            _ => format!(r#"((input) => invokeRpc("{cmd}", input))"#),
        },
        EntryKind::Command => format!(r#"((input) => invokeCommand("{cmd}", input))"#),
        EntryKind::Subscription => format!(r#"((input) => subscribeViaTauri("{cmd}", input))"#),
    }
}

/// Desktop handler list. Each `#[harmony_export]` gets a
/// `#[tauri::command]` wrapper fn in its source module (see
/// `harmony-protocol-macros::export::build_desktop_wrapper`).
/// Subscriptions additionally take `subscription_id` +
/// `Channel<StreamEvent<C>>`. The builtin `harmony_unsubscribe` cancels
/// a subscription pump by id.
///
/// The generated macro expands to `::tauri::generate_handler![...]` over
/// every wrapper plus the builtin. The file is `include!`d by the Tauri
/// shell, so the macro is defined in the crate that calls it and every
/// path is absolute into `harmony-protocol`.
fn render_handlers(entries: &[EntryRow]) -> String {
    let mut lines: Vec<String> =
        vec!["        ::harmony_protocol::desktop::harmony_unsubscribe,".into()];
    lines.extend(
        entries
            .iter()
            .sorted_by(|a, b| a.wire.cmp(b.wire))
            .map(|e| format!("        ::{}::{},", e.module, e.wire.replace('.', "_"))),
    );
    let body = lines.join("\n");

    formatdoc! {"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen

        macro_rules! harmony_handlers {{
            () => {{
                ::tauri::generate_handler![
        {body}
                ]
            }};
        }}
    "}
}
