use std::collections::BTreeMap;

use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use super::entries::{EntryRow, group_by_kind, snapshot_map};

/// One target's dispatch table. `call` is the only real per-target
/// difference — the expression that reaches that target's binding for a
/// given entry. `None` means the target has no binding yet: the table
/// degenerates to `Partial<…> = {}` so dependent imports still resolve.
pub(super) struct DispatchTable {
    pub(super) prefix: &'static str,
    pub(super) imports: &'static str,
    pub(super) call: Option<fn(&EntryRow, EntryKind) -> String>,
}

pub(super) fn render(table: &DispatchTable, entries: &[EntryRow]) -> String {
    let by_kind = group_by_kind(entries);
    let imports = table.imports;
    let note = if table.call.is_some() {
        "// Regenerate: harmony codegen".to_owned()
    } else {
        format!(
            "// Stub: {} transport not yet wired. Populate when the binding lands.",
            table.prefix
        )
    };

    let rpc = block(
        table,
        "Rpc",
        "RpcMap",
        &body(table, &by_kind[&EntryKind::Rpc], EntryKind::Rpc, "RpcMap"),
    );
    let commands = block(
        table,
        "Commands",
        "CommandMap",
        &body(
            table,
            &by_kind[&EntryKind::Command],
            EntryKind::Command,
            "CommandMap",
        ),
    );
    let subscriptions = block(
        table,
        "Subscriptions",
        "SubscriptionMap",
        &subscription_body(
            table,
            &by_kind[&EntryKind::Subscription],
            &snapshot_map(entries),
        ),
    );

    formatdoc! {r"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        {note}
        /* eslint-disable */

        {imports}

        {rpc}

        {commands}

        {subscriptions}
    "}
}

/// An empty body collapses to `{}` and downgrades the annotation to
/// `Partial<…>` — a mapped type over a populated map cannot be satisfied
/// by an empty object.
fn block(table: &DispatchTable, name: &str, map: &str, body: &str) -> String {
    let prefix = table.prefix;
    let ty = if table.call.is_some() {
        format!("{{ [K in keyof {map}]: {map}[K] }}")
    } else {
        format!("Partial<{map}>")
    };
    if body.is_empty() {
        format!("export const {prefix}{name}: {ty} = {{}};")
    } else {
        format!("export const {prefix}{name}: {ty} = {{\n{body}\n}};")
    }
}

fn body(table: &DispatchTable, entries: &[&EntryRow], kind: EntryKind, map: &str) -> String {
    let Some(call) = table.call else {
        return String::new();
    };
    entries
        .iter()
        .map(|e| {
            format!(
                r#"  "{wire}": {call} as {map}["{wire}"],"#,
                wire = e.wire,
                call = call(e, kind),
            )
        })
        .join("\n")
}

fn subscription_body(
    table: &DispatchTable,
    entries: &[&EntryRow],
    snapshots: &BTreeMap<&str, &str>,
) -> String {
    let Some(call) = table.call else {
        return String::new();
    };
    entries
        .iter()
        .map(|e| {
            let snapshot = snapshots
                .get(e.wire)
                .map(|s| format!(r#", snapshot: "{s}""#))
                .unwrap_or_default();
            format!(
                r#"  "{wire}": {{ fn: {call} as SubscriptionMap["{wire}"]["fn"]{snapshot} }},"#,
                wire = e.wire,
                call = call(e, EntryKind::Subscription),
            )
        })
        .join("\n")
}
