use std::collections::{BTreeMap, BTreeSet};

use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use super::entries::{EntryRow, group_by_kind, snapshot_map};

/// Emit the transport-agnostic `maps.generated.ts` — wire-name → typed
/// `Rpc/Command/Subscription` fn signatures, name arrays, snapshot map.
/// Consumed by every per-target dispatch module.
pub(super) fn render(entries: &[EntryRow], references: &BTreeSet<String>) -> String {
    let by_kind = group_by_kind(entries);
    let rpc = &by_kind[&EntryKind::Rpc];
    let cmd = &by_kind[&EntryKind::Command];
    let sub = &by_kind[&EntryKind::Subscription];

    let imports = rpc_map_imports(references);
    let rpc_map = rpc_map_body(rpc);
    let command_map = command_map_body(cmd);
    let subscription_map = subscription_map_body(sub);
    let rpc_names = wire_list(rpc);
    let command_names = wire_list(cmd);
    let subscription_names = wire_list(sub);
    let snapshots = snapshot_body(&snapshot_map(entries));

    formatdoc! {r#"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen
        /* eslint-disable */

        import type {{
        {imports}
        }} from "./types.generated";

        export type RpcFn<I, O> = (input: I) => Promise<{{ ok: true; value: O }} | {{ ok: false; error: HarmonyError }}>;
        export type CommandFn<I> = (input: I) => Promise<{{ ok: true }} | {{ ok: false; error: HarmonyError }}>;
        export type SubscriptionFn<I, Init, Chunk> = (input: I) => Promise<{{ ok: true; initial: Init; stream: ReadableStream<Chunk> }} | {{ ok: false; error: HarmonyError }}>;
        export type SubscriptionEntry<Fn> = {{ fn: Fn; snapshot?: string }};

        export type RpcMap = {{
        {rpc_map}
        }};

        export type CommandMap = {{
        {command_map}
        }};

        export type SubscriptionMap = {{
        {subscription_map}
        }};

        export const rpcNames = [
        {rpc_names}
        ] as const;

        export const commandNames = [
        {command_names}
        ] as const;

        export const subscriptionNames = [
        {subscription_names}
        ] as const;

        export type RpcName = typeof rpcNames[number];
        export type CommandName = typeof commandNames[number];
        export type SubscriptionName = typeof subscriptionNames[number];

        export const subscriptionSnapshots: Partial<Record<SubscriptionName, RpcName>> = {{
        {snapshots}
        }};
    "#}
}

/// `HarmonyError` is referenced by the hand-written `RpcFn`/`CommandFn`
/// aliases in the template rather than by any entry signature, so it is
/// seeded rather than collected.
fn rpc_map_imports(references: &BTreeSet<String>) -> String {
    references
        .iter()
        .map(String::as_str)
        .chain(std::iter::once("HarmonyError"))
        .collect::<BTreeSet<_>>()
        .iter()
        .map(|n| format!("  {n},"))
        .join("\n")
}

fn rpc_map_body(rpc: &[&EntryRow]) -> String {
    rpc.iter()
        .map(|e| format!(r#"  "{}": RpcFn<{}, {}>;"#, e.wire, e.input_ts, e.output_ts))
        .join("\n")
}

fn command_map_body(cmd: &[&EntryRow]) -> String {
    cmd.iter()
        .map(|e| format!(r#"  "{}": CommandFn<{}>;"#, e.wire, e.input_ts))
        .join("\n")
}

fn subscription_map_body(sub: &[&EntryRow]) -> String {
    sub.iter()
        .map(|e| {
            format!(
                r#"  "{}": SubscriptionEntry<SubscriptionFn<{}, {}, {}>>;"#,
                e.wire, e.input_ts, e.initial_ts, e.chunk_ts,
            )
        })
        .join("\n")
}

fn wire_list(entries: &[&EntryRow]) -> String {
    entries
        .iter()
        .map(|e| format!(r#"  "{}","#, e.wire))
        .join("\n")
}

fn snapshot_body(snapshots: &BTreeMap<&str, &str>) -> String {
    snapshots
        .iter()
        .map(|(sub, rpc)| format!(r#"  "{sub}": "{rpc}","#))
        .join("\n")
}
