use std::collections::{BTreeMap, BTreeSet};

use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use super::entries::{EntryRow, group_by_kind, snapshot_map};

/// Emit the transport-agnostic `maps.generated.ts` — wire-name → typed
/// `Rpc/Command/Subscription` fn signatures, name arrays, snapshot map.
/// Consumed by every per-target dispatch module.
pub(super) fn render(entries: &[EntryRow]) -> String {
    let by_kind = group_by_kind(entries);
    let rpc = &by_kind[&EntryKind::Rpc];
    let cmd = &by_kind[&EntryKind::Command];
    let sub = &by_kind[&EntryKind::Subscription];

    let imports = rpc_map_imports(entries);
    let rpc_map = rpc_map_body(rpc);
    let command_map = command_map_body(cmd);
    let subscription_map = subscription_map_body(sub);
    let rpc_names = wire_list(rpc);
    let command_names = wire_list(cmd);
    let subscription_names = wire_list(sub);
    let snapshots = snapshot_body(&snapshot_map(entries));

    formatdoc! {r#"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen
        /* eslint-disable */

        import type {{
        {imports}
        }} from "./types.generated";

        export type RpcFn<I, O> = (input: I) => Promise<{{ ok: true; value: O }} | {{ ok: false; error: HarmonyError }}>;
        export type CommandFn<I> = (input: I) => Promise<{{ ok: true }} | {{ ok: false; error: HarmonyError }}>;
        export type SubscriptionFn<I, Init, Chunk> = (input: I) => Promise<{{ ok: true; initial: Init; stream: ReadableStream<Chunk> }} | {{ ok: false; error: HarmonyError }}>;
        export type SubscriptionEntry<Fn> = {{ fn: Fn; snapshot?: string }};

        export type RpcMap = {{
        {rpc_map}
        }};

        export type CommandMap = {{
        {command_map}
        }};

        export type SubscriptionMap = {{
        {subscription_map}
        }};

        export const rpcNames = [
        {rpc_names}
        ] as const;

        export const commandNames = [
        {command_names}
        ] as const;

        export const subscriptionNames = [
        {subscription_names}
        ] as const;

        export type RpcName = typeof rpcNames[number];
        export type CommandName = typeof commandNames[number];
        export type SubscriptionName = typeof subscriptionNames[number];

        export const subscriptionSnapshots: Partial<Record<SubscriptionName, RpcName>> = {{
        {snapshots}
        }};
    "#}
}

/// Walk each entry's TS strings and pull out the bare named types
/// referenced (e.g. `LoginRequest`, `RoomData[]` → `RoomData`). Filters
/// TS primitives so the import list only includes user-defined wire
/// types from `./types.generated`.
fn collect_map_referenced_names(entries: &[EntryRow]) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    names.insert("HarmonyError".to_string());
    for entry in entries {
        for s in [
            Some(entry.input_ts),
            entry.output_ts,
            entry.initial_ts,
            entry.chunk_ts,
        ]
        .into_iter()
        .flatten()
        {
            for ident in extract_idents(s) {
                names.insert(ident);
            }
        }
    }
    names
}

fn extract_idents(ts: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut current = String::new();
    for c in ts.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            current.push(c);
        } else if !current.is_empty() {
            if is_named_type(&current) {
                out.push(std::mem::take(&mut current));
            } else {
                current.clear();
            }
        }
    }
    if !current.is_empty() && is_named_type(&current) {
        out.push(current);
    }
    out
}

fn is_named_type(name: &str) -> bool {
    // Skip TS primitives + lowercase keywords. Named user types start
    // with ASCII uppercase.
    name.chars().next().is_some_and(|c| c.is_ascii_uppercase())
}

fn rpc_map_imports(entries: &[EntryRow]) -> String {
    collect_map_referenced_names(entries)
        .iter()
        .map(|n| format!("  {n},"))
        .join("\n")
}

fn rpc_map_body(rpc: &[&EntryRow]) -> String {
    rpc.iter()
        .map(|e| {
            format!(
                r#"  "{}": RpcFn<{}, {}>;"#,
                e.wire,
                e.input_ts,
                e.output_ts.unwrap_or("void"),
            )
        })
        .join("\n")
}

fn command_map_body(cmd: &[&EntryRow]) -> String {
    cmd.iter()
        .map(|e| format!(r#"  "{}": CommandFn<{}>;"#, e.wire, e.input_ts))
        .join("\n")
}

fn subscription_map_body(sub: &[&EntryRow]) -> String {
    sub.iter()
        .map(|e| {
            format!(
                r#"  "{}": SubscriptionEntry<SubscriptionFn<{}, {}, {}>>;"#,
                e.wire,
                e.input_ts,
                e.initial_ts.unwrap_or("unknown"),
                e.chunk_ts.unwrap_or("unknown"),
            )
        })
        .join("\n")
}

fn wire_list(entries: &[&EntryRow]) -> String {
    entries
        .iter()
        .map(|e| format!(r#"  "{}","#, e.wire))
        .join("\n")
}

fn snapshot_body(snapshots: &BTreeMap<&str, &str>) -> String {
    snapshots
        .iter()
        .map(|(sub, rpc)| format!(r#"  "{sub}": "{rpc}","#))
        .join("\n")
}
