use std::path::Path;

use anyhow::{Context, Result, anyhow};
use indoc::formatdoc;

use super::entries::EntryRow;

const NATIVE_DISPATCH_OUTPUT_PATH: &str = "apps/mobile/src/transport/native/dispatch.generated.ts";

/// Run the mobile target. Currently emits a `Partial<...>` stub — real
/// dispatch lands when the uniffi-backed `harmony-bindings-mobile` is
/// wired through. Until then the file exists so dependent imports
/// resolve.
pub(super) fn run(root: &Path, _entries: &[EntryRow]) -> Result<()> {
    let path = root.join(NATIVE_DISPATCH_OUTPUT_PATH);
    std::fs::create_dir_all(
        path.parent()
            .ok_or_else(|| anyhow!("mobile dispatch output path has no parent"))?,
    )?;
    std::fs::write(&path, render_stub()).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

fn render_stub() -> String {
    formatdoc! {r#"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Stub: mobile (native) transport not yet wired. Populate when the binding lands.
        /* eslint-disable */

        import type {{ RpcMap, CommandMap, SubscriptionMap }} from "@harmony/core/protocol/maps.generated";

        export const nativeRpc: Partial<RpcMap> = {{}};
        export const nativeCommands: Partial<CommandMap> = {{}};
        export const nativeSubscriptions: Partial<SubscriptionMap> = {{}};
    "#}
}
