use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};
use harmony_protocol::EntryKind;
use indoc::formatdoc;
use itertools::Itertools;

use std::collections::BTreeMap;

use super::entries::{EntryRow, group_by_kind, snapshot_map};

const HARMONY_PROTOCOL_CRATE: &str = "crates/harmony-bindings-web";
const WASM_OUT_DIR: &str = "packages/wasm";
const WASM_DTS_PATH: &str = "packages/wasm/wasm.d.ts";
const WEB_DISPATCH_OUTPUT_PATH: &str = "packages/core/lib/transport/web/dispatch.generated.ts";

/// Run the full web target pipeline: build wasm, append wire types to
/// `wasm.d.ts`, write the populated web dispatch table.
pub(super) fn run(
    root: &Path,
    release: bool,
    types_source: &str,
    entries: &[EntryRow],
) -> Result<()> {
    build_wasm(root, release)?;
    append_types_to_wasm_dts(&root.join(WASM_DTS_PATH), types_source)?;

    let dispatch_path = root.join(WEB_DISPATCH_OUTPUT_PATH);
    std::fs::create_dir_all(
        dispatch_path
            .parent()
            .ok_or_else(|| anyhow!("web dispatch output path has no parent"))?,
    )?;
    std::fs::write(&dispatch_path, render_dispatch(entries))
        .with_context(|| format!("writing {}", dispatch_path.display()))?;
    Ok(())
}

/// Invoke `wasm-pack build` against the web bindings crate. Output pkg is
/// `@harmony/harmony-bindings-web` under `packages/wasm`.
fn build_wasm(root: &Path, release: bool) -> Result<()> {
    let crate_path = root.join(HARMONY_PROTOCOL_CRATE);
    let out_dir = root.join(WASM_OUT_DIR);

    let mut cmd = Command::new("wasm-pack");
    cmd.arg("build").arg(&crate_path);
    if !release {
        cmd.arg("--dev");
    }
    cmd.arg("--target")
        .arg("web")
        .arg("--scope")
        .arg("harmony")
        .arg("--out-dir")
        .arg(&out_dir)
        .arg("--out-name")
        .arg("wasm");

    let status = cmd
        .status()
        .context("failed to spawn `wasm-pack` — is it installed and on PATH?")?;
    if !status.success() {
        bail!("wasm-pack exited with status {status}");
    }
    Ok(())
}

/// Append the codegen'd type declarations to the wasm-bindgen-generated
/// `wasm.d.ts`. After this, `@harmony/harmony-bindings-web` is the single
/// import source for both runtime fn bindings and the wire type
/// definitions referenced by `wasm_bindgen(typescript_type = "Name")`.
fn append_types_to_wasm_dts(wasm_dts: &Path, types_source: &str) -> Result<()> {
    let existing = std::fs::read_to_string(wasm_dts)
        .with_context(|| format!("reading {}", wasm_dts.display()))?;
    let combined = format!(
        "{existing}\n\n// --- Wire types (mirrored from harmony codegen) ---\n{types_source}"
    );
    std::fs::write(wasm_dts, combined)
        .with_context(|| format!("writing {}", wasm_dts.display()))?;
    Ok(())
}

fn render_dispatch(entries: &[EntryRow]) -> String {
    let by_kind = group_by_kind(entries);
    let rpc_dispatch = rpc_body(&by_kind[&EntryKind::Rpc]);
    let command_dispatch = command_body(&by_kind[&EntryKind::Command]);
    let subscription_dispatch =
        subscription_body(&by_kind[&EntryKind::Subscription], &snapshot_map(entries));

    formatdoc! {r#"
        // AUTO-GENERATED by harmony codegen. Do not edit.
        // Regenerate: harmony codegen
        /* eslint-disable */

        import * as wasm from "@harmony/harmony-bindings-web";
        import type {{ RpcMap, CommandMap, SubscriptionMap }} from "../../protocol/maps.generated";

        export const webRpc: {{ [K in keyof RpcMap]: RpcMap[K] }} = {{
        {rpc_dispatch}
        }};

        export const webCommands: {{ [K in keyof CommandMap]: CommandMap[K] }} = {{
        {command_dispatch}
        }};

        export const webSubscriptions: {{ [K in keyof SubscriptionMap]: SubscriptionMap[K] }} = {{
        {subscription_dispatch}
        }};
    "#}
}

fn rpc_body(rpc: &[&EntryRow]) -> String {
    rpc.iter()
        .map(|e| {
            format!(
                r#"  "{wire}": wasm.{js} as RpcMap["{wire}"],"#,
                wire = e.wire,
                js = e.js,
            )
        })
        .join("\n")
}

fn command_body(cmd: &[&EntryRow]) -> String {
    cmd.iter()
        .map(|e| {
            format!(
                r#"  "{wire}": wasm.{js} as CommandMap["{wire}"],"#,
                wire = e.wire,
                js = e.js,
            )
        })
        .join("\n")
}

fn subscription_body(sub: &[&EntryRow], snapshots: &BTreeMap<&str, &str>) -> String {
    sub.iter()
        .map(|e| {
            let snapshot = snapshots
                .get(e.wire)
                .map(|s| format!(r#", snapshot: "{s}""#))
                .unwrap_or_default();
            format!(
                r#"  "{wire}": {{ fn: wasm.{js} as SubscriptionMap["{wire}"]["fn"]{snapshot} }},"#,
                wire = e.wire,
                js = e.js,
            )
        })
        .join("\n")
}
