// AUTO-GENERATED by harmony codegen. Do not edit.
// Regenerate: harmony codegen

macro_rules! harmony_handlers {
    () => {
        ::tauri::generate_handler![
        ::harmony_protocol::desktop::harmony_poll,
        ::harmony_protocol::desktop::harmony_unsubscribe,
        ::harmony_protocol::auth::auth_login,
        ::harmony_protocol::auth::auth_logout,
        ::harmony_protocol::auth::auth_restore,
        ::harmony_protocol::diagnostics::diagnostics_ping,
        ::harmony_protocol::lifecycle::lifecycle_warm,
        ::harmony_protocol::media::media_fetch,
        ::harmony_protocol::media::media_upload,
        ::harmony_protocol::rooms::members_get,
        ::harmony_protocol::rooms::members_subscribe,
        ::harmony_protocol::rooms::rooms_get_all,
        ::harmony_protocol::rooms::rooms_subscribe_in_space,
        ::harmony_protocol::spaces::spaces_create,
        ::harmony_protocol::spaces::spaces_create_room,
        ::harmony_protocol::spaces::spaces_descendants,
        ::harmony_protocol::spaces::spaces_get,
        ::harmony_protocol::spaces::spaces_subscribe,
        ::harmony_protocol::sync::sync_start,
        ::harmony_protocol::sync::sync_stop,
        ::harmony_protocol::timeline::timeline_edit,
        ::harmony_protocol::timeline::timeline_focus_on_event,
        ::harmony_protocol::timeline::timeline_get_room_state,
        ::harmony_protocol::timeline::timeline_mark_as_read,
        ::harmony_protocol::timeline::timeline_paginate,
        ::harmony_protocol::timeline::timeline_redact,
        ::harmony_protocol::timeline::timeline_return_to_live,
        ::harmony_protocol::timeline::timeline_send,
        ::harmony_protocol::timeline::timeline_subscribe,
        ::harmony_protocol::timeline::timeline_toggle_reaction,
        ]
    };
}
