// AUTO-GENERATED by harmony codegen. Do not edit.
// Regenerate: harmony codegen
/* eslint-disable */

import * as wasm from "@harmony/harmony-bindings-web";
import type { RpcMap, CommandMap, SubscriptionMap } from "../../protocol/maps.generated";

export const webRpc: { [K in keyof RpcMap]: RpcMap[K] } = {
  "auth.login": wasm.authLogin as RpcMap["auth.login"],
  "auth.restore": wasm.authRestoreSession as RpcMap["auth.restore"],
  "diagnostics.ping": wasm.diagnosticsPing as RpcMap["diagnostics.ping"],
  "lifecycle.warm": wasm.lifecycleWarm as RpcMap["lifecycle.warm"],
  "media.fetch": wasm.mediaFetch as RpcMap["media.fetch"],
  "media.upload": wasm.mediaUpload as RpcMap["media.upload"],
  "members.get": wasm.membersGetMembers as RpcMap["members.get"],
  "rooms.get_all": wasm.roomsGetAll as RpcMap["rooms.get_all"],
  "spaces.create": wasm.spacesCreateSpace as RpcMap["spaces.create"],
  "spaces.create_room": wasm.spacesCreateRoom as RpcMap["spaces.create_room"],
  "spaces.descendants": wasm.spacesGetDescendants as RpcMap["spaces.descendants"],
  "spaces.get": wasm.spacesGet as RpcMap["spaces.get"],
  "timeline.edit": wasm.timelineEditMessage as RpcMap["timeline.edit"],
  "timeline.focus_on_event": wasm.timelineFocusOnEvent as RpcMap["timeline.focus_on_event"],
  "timeline.get_room_state": wasm.timelineGetRoomState as RpcMap["timeline.get_room_state"],
  "timeline.paginate": wasm.timelinePaginateRoom as RpcMap["timeline.paginate"],
  "timeline.redact": wasm.timelineRedactMessage as RpcMap["timeline.redact"],
  "timeline.return_to_live": wasm.timelineReturnToLive as RpcMap["timeline.return_to_live"],
  "timeline.send": wasm.timelineSendMessage as RpcMap["timeline.send"],
  "timeline.toggle_reaction": wasm.timelineToggleReaction as RpcMap["timeline.toggle_reaction"],
};

export const webCommands: { [K in keyof CommandMap]: CommandMap[K] } = {
  "auth.logout": wasm.authLogout as CommandMap["auth.logout"],
  "sync.stop": wasm.syncStopSync as CommandMap["sync.stop"],
  "timeline.mark_as_read": wasm.timelineMarkAsRead as CommandMap["timeline.mark_as_read"],
};

export const webSubscriptions: { [K in keyof SubscriptionMap]: SubscriptionMap[K] } = {
  "members.subscribe": { fn: wasm.membersSubscribeMembers as SubscriptionMap["members.subscribe"]["fn"] },
  "rooms.subscribe_in_space": { fn: wasm.roomsSubscribeInSpace as SubscriptionMap["rooms.subscribe_in_space"]["fn"] },
  "spaces.subscribe": { fn: wasm.spacesSubscribe as SubscriptionMap["spaces.subscribe"]["fn"] },
  "sync.start": { fn: wasm.syncStartSync as SubscriptionMap["sync.start"]["fn"] },
  "timeline.subscribe": { fn: wasm.timelineSubscribeRoom as SubscriptionMap["timeline.subscribe"]["fn"] },
};
