version = 1

[schema]

[[schema.tables]]
id = 0
name = "custom_statuses"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "mxid"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "emoji_name"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "emoji_id"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "emoji_animated"
ty = "Bool"
storage_ty = "Boolean"

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "text"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "expires_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 8 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_custom_statuses_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_custom_statuses_by_mxid"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "invite_links"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "code"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "space_mxid"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "creator_mxid"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "max_uses"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "use_count"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 6 }
name = "expires_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 7 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 8 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_invite_links_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_invite_links_by_code"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
