[package]
name = "harmony-desktop"
version = "0.0.0"
edition = "2024"

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
harmony-protocol = { workspace = true, features = ["desktop"] }
tauri = { workspace = true, features = [] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
