// AUTO-GENERATED by harmony codegen. Do not edit.
// Regenerate: harmony codegen

#[macro_export]
macro_rules! harmony_handlers {
    () => {
        ::tauri::generate_handler![
        $crate::desktop::harmony_unsubscribe,
        $crate::auth::auth_login,
        $crate::auth::auth_logout,
        $crate::auth::auth_restore,
        $crate::diagnostics::diagnostics_ping,
        $crate::lifecycle::lifecycle_warm,
        $crate::media::media_fetch,
        $crate::media::media_upload,
        $crate::rooms::members_get,
        $crate::rooms::members_subscribe,
        $crate::rooms::rooms_get_all,
        $crate::rooms::rooms_subscribe_in_space,
        $crate::spaces::spaces_create,
        $crate::spaces::spaces_create_room,
        $crate::spaces::spaces_descendants,
        $crate::spaces::spaces_get,
        $crate::spaces::spaces_subscribe,
        $crate::sync::sync_start,
        $crate::sync::sync_stop,
        $crate::timeline::timeline_edit,
        $crate::timeline::timeline_focus_on_event,
        $crate::timeline::timeline_get_room_state,
        $crate::timeline::timeline_mark_as_read,
        $crate::timeline::timeline_paginate,
        $crate::timeline::timeline_redact,
        $crate::timeline::timeline_return_to_live,
        $crate::timeline::timeline_send,
        $crate::timeline::timeline_subscribe,
        $crate::timeline::timeline_toggle_reaction,
        ]
    };
}
