[package]
name = "harmony-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "harmony"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7"
url = "2"
walrus = "0.26"
