[package]
name = "harmony-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "harmony"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indoc = "2"
itertools = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

harmony-protocol = { path = "../../packages/harmony-protocol" }
specta = { version = "=2.0.0-rc.24", features = ["derive"] }
specta-serde = "=0.0.11"
specta-typescript = "=0.0.11"
inventory = "0.3"
