[package]
name = "harmony-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "harmony"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indoc = "2"
itertools = "0.14"
serde = { workspace = true }
serde_json = { workspace = true }

harmony-protocol = { workspace = true }
specta = { workspace = true }
specta-serde = "=0.0.11"
specta-typescript = { workspace = true }
inventory = { workspace = true }
